### ISSUE TITLE
Converting TS to JS Error

### ISSUE THREAD

**Issue by rbrisita** [uuid25/javascript#1]
`import { Uuid25 } from "uuid25"` gets converted to `const uuid25_1 = require("uuid25");` and breaks with error:

```shell
Error [ERR_REQUIRE_ESM]: require() of ES Module node_modules/uuid25/uuid25.js from <file_w_import> not supported.
Instead change the require of uuid25.js in <file_w_import> to a dynamic import() which is available in all CommonJS modules.
```

It still breaks with various dynamic imports. It would be best to support all module types.

The only way that it works is with `eval` but that can be dangerous and not recommended.

`eval('import(\'uuid25\').then(body => console.log(\'body\', body))');`

**Comment by LiosK** [comment]
Please try [v0.1.4](https://github.com/uuid25/javascript/releases/tag/v0.1.4).
